Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'lib/realdebrid/version.rb'
    - 'Rakefile'
    - 'realdebrid.gemspec'